name: Conditional Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1 completed!"

  manual-step:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.inputs.continue == 'true' # 检查是否继续
    steps:
      - name: Step 2
        run: echo "Step 2 completed!"
