name: Auto and Manual Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Build
        run: echo "Building project..."
      - name: Step 2 - Test
        run: echo "Running tests..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production # 设置需要审批的环境
    steps:
      - name: Step 3 - Awaiting Approval
        run: echo "Deploying project to production after approval..."
