name: Single Pipeline with Manual Trigger

on:
  push:
    branches:
      - main

jobs:
  # 自动执行步骤
  auto-steps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Step 1 - Build
        run: pwd
      - name: ls
        run: ls
      - name: Step 2 - Test
        run: echo "Running tests..."

  # 手动触发的步骤
  manual-steps:
    needs: auto-steps
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test
    environment:
      name: production  # 需要审批的环境
    steps:
      - name: Step 3 - Manual Approval
        run: ls

